### ISSUE TITLE
Gila service is shut down

### ISSUE THREAD

**Issue by clopezno** [SOM-Research/gila#34]
Using the tool  The tool is available at http://som-research.github.io/gila.
It is imposible analyze a Github repository using that url.

**Comment by valeriocos** [comment]
Sorry for the inconvience. All should be back to normal soon (no more than a couple of weeks)..

**Comment by jlcanovas** [comment]
Hi @clopezno, we are having a look at this issue. We need to do some work in the backend to fix the problem.

**Comment by jlcanovas** [comment]
Hi @clopezno, we have been working to addressing this issue. The service is now online again.

Please, check it out at http://som-research.uoc.edu/tools/gila/

Thanks!
