### ISSUE TITLE
Selecting an Github project 

### ISSUE THREAD

**Issue by clopezno** [SOM-Research/gila#36]
I´m testing Gila service and I have a question.
Can I analyze any Github project or just those loaded in combobox?
For example, I would like to analize pushtorefresh/storio (https://github.com/pushtorefresh/storio/issues), is it possible?

**Comment by jlcanovas** [comment]
For the time being, you can only query the projects loaded in the combobox (they are part of the [GHTorrent ](http://ghtorrent.org/) dataset)

**Comment by clopezno** [comment]
Thank you very much.
