### ISSUE TITLE
Gila service shutdown

### ISSUE THREAD

**Issue by clopezno** [SOM-Research/gila#37]
The same problem described in #34.
Regards.

**Comment by jlcanovas** [comment]
Hi,

the service seems to be working properly. Could you please check that you are accessing to http://som-research.uoc.edu/tools/gila?

**Comment by clopezno** [comment]
I am using in my laptop two Web browsers: Firefox and Chrome.
Gila is working fine with FireFox but no with Chrome. Gila graphical user interface doesn´t load  Github repositories names on combobox.
Greetings.

**Comment by jlcanovas** [comment]
Could you please send us a snapshot of the Chrome console? To investigate any problem loading/interpreting the webpage?

**Comment by clopezno** [comment]
Here you are the console messages.

```
http://som-research.github.io/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
http://atlanmodexp.info.emn.fr:8800/gila/LabelAnalysisServlet?event=getproj…ts&featureClass=P&style=full&maxRows=50&username=jqwidgets&_=1473783912754 Failed to load resource: net::ERR_CONNECTION_RESET
http://atlanmodexp.info.emn.fr:8800/gila/LabelAnalysisServlet?event=getproj…=P&style=full&maxRows=50&username=jqwidgets&_=1473783916388&searchstring=t Failed to load resource: net::ERR_CONNECTION_RESET
http://atlanmodexp.info.emn.fr:8800/gila/LabelAnalysisServlet?event=getproj…P&style=full&maxRows=50&username=jqwidgets&_=1473783922874&searchstring=tt Failed to load resource: net::ERR_CONNECTION_RESET
jqxdata.js:7 GET http://atlanmodexp.info.emn.fr:8800/gila/LabelAnalysisServlet?event=getproj…=P&style=full&maxRows=50&username=jqwidgets&_=1473784044881&searchstring=t net::ERR_CONNECTION_RESETsend @ jqxdata.js:7ajax @ jqxdata.js:7dataBind @ jqxdata.js:7search @ initIndex.js:62(anonymous function) @ jqxcombobox.js:7
```

**Comment by jlcanovas** [comment]
Thks for the report, let me have a look at the problem, I'll come back asap.

**Comment by jlcanovas** [comment]
It's strange you are getting errors regarding our old server (i.e., "atlanmodexp"). We have been testing the access and everything looks to work fine.  Anyway, I have detected old traces to the previous server in one JavaScript file. Maybe it was triggering your problem.

Please, tell us if you can now access the site correctly. Thanks!

**Comment by clopezno** [comment]
Yes, I can access to the site correctly from my  laptop with two Web browsers: Firefox and Chrome.
Thank you for your work !

A curiosity...
I´ve tested with my Samsung table, two Web browsers again (Chrome and Android browser) , and I have the same problem described in #34.  I don´t know how to get log file in my Samsung table.

Greetings.

**Comment by jlcanovas** [comment]
Thks for the info.

For the problem in your table, try to delete the cache. If the problem is the same, it means the browser is trying to contact our old server. The last version of the webpage has this fixed and the problem should not appear.

**Comment by clopezno** [comment]
One of my problems was that I clicked on url 
available in GitHub README file  http://som-research.github.io/gila/.
I think that it is necessary update it with http://som-research.uoc.edu/tools/gila.

**Comment by jlcanovas** [comment]
Thanks for the comments, I've just updated the README
