### ISSUE TITLE
Does this tool still works?

### ISSUE THREAD

**Issue by Zimmi48** [SOM-Research/gila#39]
If yes, would you mind fixing the URLs provided in the README? Right now, they lead to a 404 page.

Thanks!

**Comment by jlcanovas** [comment]
Hi @Zimmi48, the tool development has been discontinued and is no longer available online. I've just updated the readme, sorry for the confusion. You can still download the code and deploy the tool in your computer, if you want to play with it.

**Comment by Zimmi48** [comment]
OK, thanks for the answer!
